<div class="container">
	<div class="valign tag_startup">
		<div class="wow_content p20">
			<div class="row tag_startup_row">
				<div class="col-lg-4 col-md-3">
					<?php if (Wo_IsMobile() == false) { ?>
					<div class="tag_startup_img">
						<h2 class="text-center tag_page_title"><?php echo $wo['lang']['follow_head']; ?></h2>
						<img src="<?php echo $wo['config']['theme_url'];?>/img/start_up/follow.png" alt="<?php echo $wo['lang']['follow']; ?>">
					</div>
					<?php } ?>
				</div>
				<div class="col-lg-8 col-md-9">
					<ul class="list-unstyled tag_steps">
						<li class="active"><div><?php echo $wo['lang']['ad_media']; ?></div></li>
						<li class="active"><div><?php echo $wo['lang']['info']; ?></div></li>
						<li class="active"><div><?php echo $wo['lang']['follow']; ?></div></li>
					</ul>
					<hr>
					<div class="wow_usr_steps text-center">
						<h4><?php echo $wo['lang']['get_latest_activity'];?></h4>
						<br><br>
						<div class="row">
							<?php
								$user_id = array();
								foreach ($wo['users'] as $wo['result']) {
									$user_id[] = $wo['result']['user_id'];
									$wo['result']['no_btn'] = true;
									echo Wo_LoadPage('start_up/user-result');
								}
								echo '<input type="hidden" name="users" id="users-id" value="' . implode(',' , $user_id) . '">';
							?>
						</div>
						<div class="clear"></div>
					</div>
					<div class="valign wow_usr_steps_cont">
						<small class="skip-step pointer" onclick="Wo_SkipStep('startup_follow');"><?php echo $wo['lang']['start_up_skip'];?></small>
						<button class="btn con-button btn-main btn-mat disable_btn" onclick="Wo_SubmitFollow();"><?php $string = str_replace('{number}', count($wo['users']), $wo['lang']['follow_num']); echo $string;?></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
function Wo_SubmitFollow() {
	$('.con-button').attr('disabled', true);
	$('.con-button').text("<?php echo $wo['lang']['please_wait'];?>");
	var users = $('#users-id').val();
	$.post(Wo_Ajax_Requests_File() + '?f=follow_users', {user:users}, function (data) {
		if (data.status == 200) {
			window.location.href = '<?php echo Wo_SeoLink('index.php?link1=start-up');?>';
		}
	});
}
</script>